---
name: Build Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: MkDocs Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and plugins
        run: pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-mermaid2-plugin

      - name: Build documentation
        run: mkdocs build --strict
