name: "Build Docs"
on:
  push:
    branches: ["main"]

jobs:
  build-docs:
    name: "Build MkDocs Site"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v7
      - name: "Set up Python Environment"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Install MkDocs and Plugins"
        run: |
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-mermaid2-plugin
      - name: "Build Documentation Site"
        run: mkdocs build --strict
