name: "Build Documentation"

on:
  push:
  pull_request:

jobs:
  build:
    name: "MkDocs Validation"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Set up Python Environment"
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Install MkDocs Dependencies"
        run: pip install mkdocs

      - name: "Execute Strict Build Validation"
        run: mkdocs build --strict
