name: Docs Auto-Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs + plugins
        run: |
          pip install mkdocs \
                     mkdocs-material \
                     mkdocs-awesome-pages-plugin \
                     mkdocs-mermaid2-plugin \
                     mkdocs-literate-nav \
                     mkdocs-redirects

      - name: Validate documentation build
        run: |
          mkdocs build --strict
